name: causal_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.9.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.12.2
  - cairo=1.18.0
  - dav1d=1.2.1
  - expat=2.7.3
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.12
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - icu=73.2
  - imath=3.1.12
  - jasper=4.2.8
  - krb5=1.21.3
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libass=0.17.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.17.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopencv=4.10.0
  - libopenvino=2024.4.0
  - libopenvino-arm-cpu-plugin=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.5.2
  - libpng=1.6.53
  - libprotobuf=5.28.2
  - librsvg=2.58.4
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - opencv=4.10.0
  - openexr=3.3.2
  - openh264=2.5.0
  - openssl=3.6.0
  - pandas=2.3.3
  - pango=1.54.0
  - pcre2=10.44
  - pip=25.3
  - pixman=0.46.4
  - pugixml=1.14
  - py-opencv=4.10.0
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - svt-av1=2.3.0
  - tbb=2022.3.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - appnope==0.1.4
      - arxiv==2.3.1
      - asttokens==3.0.1
      - attrs==25.4.0
      - autograd==1.8.0
      - blinker==1.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.18
      - decorator==5.2.1
      - distro==1.9.0
      - executing==2.2.1
      - feedparser==6.0.12
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gcastle==1.0.4rc1
      - graphviz==0.21
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.11
      - imageio==2.37.2
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - langchain==1.2.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.2.1
      - langchain-openai==1.1.3
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.5
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.3.0
      - langsmith==0.4.59
      - lazy-loader==0.4
      - lingam==1.12.1
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numdifftools==0.9.42
      - openai==2.12.0
      - orjson==3.11.5
      - ormsgpack==1.12.1
      - packaging==25.0
      - parso==0.8.5
      - patsy==1.0.2
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - progressbar2==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - psy==0.0.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygam==0.11.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - python-utils==3.9.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - scikit-image==0.25.2
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - semopy==2.3.11
      - sgmllib3k==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.45
      - stack-data==0.6.3
      - statsmodels==0.14.6
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.12.12
      - tiktoken==0.12.0
      - torch==2.9.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uuid-utils==0.12.0
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wget==3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /Users/kbarakat/miniconda3/envs/causal_env
